# this is an example on how to setup CI to generate CC and upload to codeclimate
name: CI

on: [push]

jobs:
  jsdoc:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Generate out folder with documentation
      run: |
        npm install
        npm run jsdoc